export const colors: { hex: string; title: string }[] = [
	{ hex: '#AD1457', title: 'Raspberry' },
	{ hex: '#F09300', title: 'Orange' },
	{ hex: '#03CE70', title: 'Emerald' },
	{ hex: '#1E3AD6', title: 'Royal Blue' },
	{ hex: '#B4006C', title: 'Magenta' },
	{ hex: '#E80B5B', title: 'Crimson' },
	{ hex: '#FBCB07', title: 'Gold' },
	{ hex: '#14A95B', title: 'Green' },
	{ hex: '#58009D', title: 'Purple' },
	{ hex: '#B4451D', title: 'Brown' },
	{ hex: '#EB0707', title: 'Red' },
	{ hex: '#D8E70B', title: 'Lime' },
	{ hex: '#00F3DD', title: 'Turquoise' },
	{ hex: '#AB1BD1', title: 'Violet' },
	{ hex: '#CA8E4D', title: 'Caramel' },
	{ hex: '#F4511E', title: 'Vermilion' },
	{ hex: '#79D816', title: 'Lime Green' },
	{ hex: '#039BE5', title: 'Azure' },
	{ hex: '#F442CD', title: 'Pink' },
	{ hex: '#878787', title: 'Grey' }
];
