create table "public"."Patouilles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."Patouilles" enable row level security;

CREATE UNIQUE INDEX "Patouilles_pkey" ON public."Patouilles" USING btree (id);

alter table "public"."Patouilles" add constraint "Patouilles_pkey" PRIMARY KEY using index "Patouilles_pkey";

grant delete on table "public"."Patouilles" to "anon";

grant insert on table "public"."Patouilles" to "anon";

grant references on table "public"."Patouilles" to "anon";

grant select on table "public"."Patouilles" to "anon";

grant trigger on table "public"."Patouilles" to "anon";

grant truncate on table "public"."Patouilles" to "anon";

grant update on table "public"."Patouilles" to "anon";

grant delete on table "public"."Patouilles" to "authenticated";

grant insert on table "public"."Patouilles" to "authenticated";

grant references on table "public"."Patouilles" to "authenticated";

grant select on table "public"."Patouilles" to "authenticated";

grant trigger on table "public"."Patouilles" to "authenticated";

grant truncate on table "public"."Patouilles" to "authenticated";

grant update on table "public"."Patouilles" to "authenticated";

grant delete on table "public"."Patouilles" to "service_role";

grant insert on table "public"."Patouilles" to "service_role";

grant references on table "public"."Patouilles" to "service_role";

grant select on table "public"."Patouilles" to "service_role";

grant trigger on table "public"."Patouilles" to "service_role";

grant truncate on table "public"."Patouilles" to "service_role";

grant update on table "public"."Patouilles" to "service_role";


